// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: gateway/middleware/jwt/v1/jwt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	PublicPaths   []string               `protobuf:"bytes,2,rep,name=public_paths,json=publicPaths,proto3" json:"public_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwt) Reset() {
	*x = Jwt{}
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwt) ProtoMessage() {}

func (x *Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_jwt_v1_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwt.ProtoReflect.Descriptor instead.
func (*Jwt) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_jwt_v1_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Jwt) GetPublicPaths() []string {
	if x != nil {
		return x.PublicPaths
	}
	return nil
}

var File_gateway_middleware_jwt_v1_jwt_proto protoreflect.FileDescriptor

const file_gateway_middleware_jwt_v1_jwt_proto_rawDesc = "" +
	"\n" +
	"#gateway/middleware/jwt/v1/jwt.proto\x12\x19gateway.middleware.jwt.v1\"@\n" +
	"\x03Jwt\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12!\n" +
	"\fpublic_paths\x18\x02 \x03(\tR\vpublicPathsB<Z:github.com/go-kratos/gateway/api/gateway/middleware/jwt/v1b\x06proto3"

var (
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescOnce sync.Once
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescData []byte
)

func file_gateway_middleware_jwt_v1_jwt_proto_rawDescGZIP() []byte {
	file_gateway_middleware_jwt_v1_jwt_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_jwt_v1_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc), len(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc)))
	})
	return file_gateway_middleware_jwt_v1_jwt_proto_rawDescData
}

var file_gateway_middleware_jwt_v1_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_middleware_jwt_v1_jwt_proto_goTypes = []any{
	(*Jwt)(nil), // 0: gateway.middleware.jwt.v1.Jwt
}
var file_gateway_middleware_jwt_v1_jwt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_middleware_jwt_v1_jwt_proto_init() }
func file_gateway_middleware_jwt_v1_jwt_proto_init() {
	if File_gateway_middleware_jwt_v1_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc), len(file_gateway_middleware_jwt_v1_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_jwt_v1_jwt_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_jwt_v1_jwt_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_jwt_v1_jwt_proto_msgTypes,
	}.Build()
	File_gateway_middleware_jwt_v1_jwt_proto = out.File
	file_gateway_middleware_jwt_v1_jwt_proto_goTypes = nil
	file_gateway_middleware_jwt_v1_jwt_proto_depIdxs = nil
}
