// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: core/v1/contest_log/contest.proto

package contest_log

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 竞赛日志消息体
type ContestLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // ID
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`                          // 平台
	ContestId     string                 `protobuf:"bytes,4,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`       // 比赛ID
	ContestName   string                 `protobuf:"bytes,5,opt,name=contest_name,json=contestName,proto3" json:"contest_name,omitempty"` // 比赛名称
	ContestUrl    string                 `protobuf:"bytes,6,opt,name=contest_url,json=contestUrl,proto3" json:"contest_url,omitempty"`    // 比赛链接
	TotalCount    int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`   // 总题数
	Time          int64                  `protobuf:"varint,10,opt,name=time,proto3" json:"time,omitempty"`                                // 比赛时间戳
	EndTime       int64                  `protobuf:"varint,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`           // 比赛结束时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestLog) Reset() {
	*x = ContestLog{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestLog) ProtoMessage() {}

func (x *ContestLog) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestLog.ProtoReflect.Descriptor instead.
func (*ContestLog) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{0}
}

func (x *ContestLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContestLog) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ContestLog) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *ContestLog) GetContestName() string {
	if x != nil {
		return x.ContestName
	}
	return ""
}

func (x *ContestLog) GetContestUrl() string {
	if x != nil {
		return x.ContestUrl
	}
	return ""
}

func (x *ContestLog) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ContestLog) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ContestLog) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 获取竞赛列表请求
type GetContestListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 限制数量
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`               // 偏移量
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`            // 平台筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestListReq) Reset() {
	*x = GetContestListReq{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestListReq) ProtoMessage() {}

func (x *GetContestListReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestListReq.ProtoReflect.Descriptor instead.
func (*GetContestListReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{1}
}

func (x *GetContestListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetContestListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetContestListReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetContestListReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 获取竞赛列表响应
type GetContestListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息
	Data          []*ContestLog          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`       // 竞赛列表数据
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestListRes) Reset() {
	*x = GetContestListRes{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestListRes) ProtoMessage() {}

func (x *GetContestListRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestListRes.ProtoReflect.Descriptor instead.
func (*GetContestListRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{2}
}

func (x *GetContestListRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetContestListRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContestListRes) GetData() []*ContestLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetContestListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取用户竞赛历史请求
type GetUserContestHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 限制数量
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`               // 时间游标
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`            // 平台筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContestHistoryReq) Reset() {
	*x = GetUserContestHistoryReq{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContestHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContestHistoryReq) ProtoMessage() {}

func (x *GetUserContestHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContestHistoryReq.ProtoReflect.Descriptor instead.
func (*GetUserContestHistoryReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserContestHistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserContestHistoryReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserContestHistoryReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetUserContestHistoryReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 获取用户竞赛历史响应
type GetUserContestHistoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息
	Data          []*ContestLog          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`       // 竞赛历史数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContestHistoryRes) Reset() {
	*x = GetUserContestHistoryRes{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContestHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContestHistoryRes) ProtoMessage() {}

func (x *GetUserContestHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContestHistoryRes.ProtoReflect.Descriptor instead.
func (*GetUserContestHistoryRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserContestHistoryRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserContestHistoryRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserContestHistoryRes) GetData() []*ContestLog {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取竞赛排行榜请求
type GetContestRankingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     string                 `protobuf:"bytes,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"` // 比赛ID
	GroupId       *int64                 `protobuf:"varint,4,opt,name=groupId,proto3,oneof" json:"groupId,omitempty"`               // 组id（不传返回全部，传具体值按组过滤，包括0）
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                         // 限制数量
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                       // 偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestRankingReq) Reset() {
	*x = GetContestRankingReq{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestRankingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestRankingReq) ProtoMessage() {}

func (x *GetContestRankingReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestRankingReq.ProtoReflect.Descriptor instead.
func (*GetContestRankingReq) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{5}
}

func (x *GetContestRankingReq) GetContestId() string {
	if x != nil {
		return x.ContestId
	}
	return ""
}

func (x *GetContestRankingReq) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GetContestRankingReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetContestRankingReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 排行榜项
type RankingItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rank           int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                                          // 排名
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 用户ID
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                           // 用户姓名
	Avatar         string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`                                       // 用户image
	Score          int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                                        // 得分
	AcCount        int32                  `protobuf:"varint,5,opt,name=ac_count,json=acCount,proto3" json:"ac_count,omitempty"`                     // 过题数
	TotalCount     int32                  `protobuf:"varint,6,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`            // 总题数
	Penalty        int32                  `protobuf:"varint,8,opt,name=penalty,proto3" json:"penalty,omitempty"`                                    // 罚时（分钟）
	ProblemResults []*ProblemResult       `protobuf:"bytes,9,rep,name=problem_results,json=problemResults,proto3" json:"problem_results,omitempty"` // 逐题结果
	GroupId        int64                  `protobuf:"varint,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                    // 用户所属团队/分组ID
	Username       string                 `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`                                  // 用户账号名
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RankingItem) Reset() {
	*x = RankingItem{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingItem) ProtoMessage() {}

func (x *RankingItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingItem.ProtoReflect.Descriptor instead.
func (*RankingItem) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{6}
}

func (x *RankingItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankingItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RankingItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RankingItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RankingItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankingItem) GetAcCount() int32 {
	if x != nil {
		return x.AcCount
	}
	return 0
}

func (x *RankingItem) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RankingItem) GetPenalty() int32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *RankingItem) GetProblemResults() []*ProblemResult {
	if x != nil {
		return x.ProblemResults
	}
	return nil
}

func (x *RankingItem) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RankingItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// 题目列
type ProblemColumn struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Index            string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`                                                // 题号，如 A/B/C
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                  // 题目名称
	ProblemKey       string                 `protobuf:"bytes,3,opt,name=problem_key,json=problemKey,proto3" json:"problem_key,omitempty"`                    // 题目标识
	ContestAccepted  int32                  `protobuf:"varint,4,opt,name=contest_accepted,json=contestAccepted,proto3" json:"contest_accepted,omitempty"`    // 赛时通过人数
	ContestAttempted int32                  `protobuf:"varint,5,opt,name=contest_attempted,json=contestAttempted,proto3" json:"contest_attempted,omitempty"` // 赛时提交人数
	UpsolveAccepted  int32                  `protobuf:"varint,6,opt,name=upsolve_accepted,json=upsolveAccepted,proto3" json:"upsolve_accepted,omitempty"`    // 赛后补题通过人数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProblemColumn) Reset() {
	*x = ProblemColumn{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemColumn) ProtoMessage() {}

func (x *ProblemColumn) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemColumn.ProtoReflect.Descriptor instead.
func (*ProblemColumn) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{7}
}

func (x *ProblemColumn) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *ProblemColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProblemColumn) GetProblemKey() string {
	if x != nil {
		return x.ProblemKey
	}
	return ""
}

func (x *ProblemColumn) GetContestAccepted() int32 {
	if x != nil {
		return x.ContestAccepted
	}
	return 0
}

func (x *ProblemColumn) GetContestAttempted() int32 {
	if x != nil {
		return x.ContestAttempted
	}
	return 0
}

func (x *ProblemColumn) GetUpsolveAccepted() int32 {
	if x != nil {
		return x.UpsolveAccepted
	}
	return 0
}

// 单用户单题结果
type ProblemResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProblemKey     string                 `protobuf:"bytes,1,opt,name=problem_key,json=problemKey,proto3" json:"problem_key,omitempty"`              // 题目标识
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                        // none/contest_ac/contest_failed/upsolve_ac
	AcceptedMinute int32                  `protobuf:"varint,3,opt,name=accepted_minute,json=acceptedMinute,proto3" json:"accepted_minute,omitempty"` // 赛时 AC 分钟数
	WrongBeforeAc  int32                  `protobuf:"varint,4,opt,name=wrong_before_ac,json=wrongBeforeAc,proto3" json:"wrong_before_ac,omitempty"`  // AC 前错误次数
	WrongAttempts  int32                  `protobuf:"varint,5,opt,name=wrong_attempts,json=wrongAttempts,proto3" json:"wrong_attempts,omitempty"`    // 未 AC 错误次数
	Upsolved       bool                   `protobuf:"varint,6,opt,name=upsolved,proto3" json:"upsolved,omitempty"`                                   // 是否赛后补题 AC
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProblemResult) Reset() {
	*x = ProblemResult{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResult) ProtoMessage() {}

func (x *ProblemResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResult.ProtoReflect.Descriptor instead.
func (*ProblemResult) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{8}
}

func (x *ProblemResult) GetProblemKey() string {
	if x != nil {
		return x.ProblemKey
	}
	return ""
}

func (x *ProblemResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProblemResult) GetAcceptedMinute() int32 {
	if x != nil {
		return x.AcceptedMinute
	}
	return 0
}

func (x *ProblemResult) GetWrongBeforeAc() int32 {
	if x != nil {
		return x.WrongBeforeAc
	}
	return 0
}

func (x *ProblemResult) GetWrongAttempts() int32 {
	if x != nil {
		return x.WrongAttempts
	}
	return 0
}

func (x *ProblemResult) GetUpsolved() bool {
	if x != nil {
		return x.Upsolved
	}
	return false
}

// 获取竞赛排行榜响应
type GetContestRankingRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                          // 状态码
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // 消息
	Contest        *ContestLog            `protobuf:"bytes,5,opt,name=contest,proto3" json:"contest,omitempty"`                                     // 竞赛历史数据
	Data           []*RankingItem         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`                                           // 排行榜数据
	Total          int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`                                        // 总参赛人数
	Problems       []*ProblemColumn       `protobuf:"bytes,6,rep,name=problems,proto3" json:"problems,omitempty"`                                   // 动态题目列
	DegradedReason string                 `protobuf:"bytes,7,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"` // 降级原因
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContestRankingRes) Reset() {
	*x = GetContestRankingRes{}
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestRankingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestRankingRes) ProtoMessage() {}

func (x *GetContestRankingRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_contest_log_contest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestRankingRes.ProtoReflect.Descriptor instead.
func (*GetContestRankingRes) Descriptor() ([]byte, []int) {
	return file_core_v1_contest_log_contest_proto_rawDescGZIP(), []int{9}
}

func (x *GetContestRankingRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetContestRankingRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContestRankingRes) GetContest() *ContestLog {
	if x != nil {
		return x.Contest
	}
	return nil
}

func (x *GetContestRankingRes) GetData() []*RankingItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetContestRankingRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetContestRankingRes) GetProblems() []*ProblemColumn {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *GetContestRankingRes) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

var File_core_v1_contest_log_contest_proto protoreflect.FileDescriptor

const file_core_v1_contest_log_contest_proto_rawDesc = "" +
	"\n" +
	"!core/v1/contest_log/contest.proto\x12\x17api.core.v1.contest_log\x1a\x1cgoogle/api/annotations.proto\"\xeb\x01\n" +
	"\n" +
	"ContestLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x04 \x01(\tR\tcontestId\x12!\n" +
	"\fcontest_name\x18\x05 \x01(\tR\vcontestName\x12\x1f\n" +
	"\vcontest_url\x18\x06 \x01(\tR\n" +
	"contestUrl\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04time\x18\n" +
	" \x01(\x03R\x04time\x12\x19\n" +
	"\bend_time\x18\v \x01(\x03R\aendTime\"v\n" +
	"\x11GetContestListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x90\x01\n" +
	"\x11GetContestListRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.api.core.v1.contest_log.ContestLogR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"}\n" +
	"\x18GetUserContestHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x81\x01\n" +
	"\x18GetUserContestHistoryRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.api.core.v1.contest_log.ContestLogR\x04data\"\x8e\x01\n" +
	"\x14GetContestRankingReq\x12\x1d\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\tR\tcontestId\x12\x1d\n" +
	"\agroupId\x18\x04 \x01(\x03H\x00R\agroupId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offsetB\n" +
	"\n" +
	"\b_groupId\"\xda\x02\n" +
	"\vRankingItem\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x19\n" +
	"\bac_count\x18\x05 \x01(\x05R\aacCount\x12\x1f\n" +
	"\vtotal_count\x18\x06 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\apenalty\x18\b \x01(\x05R\apenalty\x12O\n" +
	"\x0fproblem_results\x18\t \x03(\v2&.api.core.v1.contest_log.ProblemResultR\x0eproblemResults\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\x03R\agroupId\x12\x1a\n" +
	"\busername\x18\v \x01(\tR\busername\"\xdd\x01\n" +
	"\rProblemColumn\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vproblem_key\x18\x03 \x01(\tR\n" +
	"problemKey\x12)\n" +
	"\x10contest_accepted\x18\x04 \x01(\x05R\x0fcontestAccepted\x12+\n" +
	"\x11contest_attempted\x18\x05 \x01(\x05R\x10contestAttempted\x12)\n" +
	"\x10upsolve_accepted\x18\x06 \x01(\x05R\x0fupsolveAccepted\"\xdc\x01\n" +
	"\rProblemResult\x12\x1f\n" +
	"\vproblem_key\x18\x01 \x01(\tR\n" +
	"problemKey\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0faccepted_minute\x18\x03 \x01(\x05R\x0eacceptedMinute\x12&\n" +
	"\x0fwrong_before_ac\x18\x04 \x01(\x05R\rwrongBeforeAc\x12%\n" +
	"\x0ewrong_attempts\x18\x05 \x01(\x05R\rwrongAttempts\x12\x1a\n" +
	"\bupsolved\x18\x06 \x01(\bR\bupsolved\"\xc0\x02\n" +
	"\x14GetContestRankingRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\acontest\x18\x05 \x01(\v2#.api.core.v1.contest_log.ContestLogR\acontest\x128\n" +
	"\x04data\x18\x03 \x03(\v2$.api.core.v1.contest_log.RankingItemR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12B\n" +
	"\bproblems\x18\x06 \x03(\v2&.api.core.v1.contest_log.ProblemColumnR\bproblems\x12'\n" +
	"\x0fdegraded_reason\x18\a \x01(\tR\x0edegradedReason2\xcb\x03\n" +
	"\aContest\x12\x87\x01\n" +
	"\x0eGetContestList\x12*.api.core.v1.contest_log.GetContestListReq\x1a*.api.core.v1.contest_log.GetContestListRes\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/core/contest/list\x12\x9f\x01\n" +
	"\x15GetUserContestHistory\x121.api.core.v1.contest_log.GetUserContestHistoryReq\x1a1.api.core.v1.contest_log.GetUserContestHistoryRes\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/core/contest/history\x12\x93\x01\n" +
	"\x11GetContestRanking\x12-.api.core.v1.contest_log.GetContestRankingReq\x1a-.api.core.v1.contest_log.GetContestRankingRes\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/core/contest/rankingBJ\n" +
	"\x17api.core.v1.contest_logP\x01Z-cwxu-algo/api/core/v1/contest_log;contest_logb\x06proto3"

var (
	file_core_v1_contest_log_contest_proto_rawDescOnce sync.Once
	file_core_v1_contest_log_contest_proto_rawDescData []byte
)

func file_core_v1_contest_log_contest_proto_rawDescGZIP() []byte {
	file_core_v1_contest_log_contest_proto_rawDescOnce.Do(func() {
		file_core_v1_contest_log_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_contest_log_contest_proto_rawDesc), len(file_core_v1_contest_log_contest_proto_rawDesc)))
	})
	return file_core_v1_contest_log_contest_proto_rawDescData
}

var file_core_v1_contest_log_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_v1_contest_log_contest_proto_goTypes = []any{
	(*ContestLog)(nil),               // 0: api.core.v1.contest_log.ContestLog
	(*GetContestListReq)(nil),        // 1: api.core.v1.contest_log.GetContestListReq
	(*GetContestListRes)(nil),        // 2: api.core.v1.contest_log.GetContestListRes
	(*GetUserContestHistoryReq)(nil), // 3: api.core.v1.contest_log.GetUserContestHistoryReq
	(*GetUserContestHistoryRes)(nil), // 4: api.core.v1.contest_log.GetUserContestHistoryRes
	(*GetContestRankingReq)(nil),     // 5: api.core.v1.contest_log.GetContestRankingReq
	(*RankingItem)(nil),              // 6: api.core.v1.contest_log.RankingItem
	(*ProblemColumn)(nil),            // 7: api.core.v1.contest_log.ProblemColumn
	(*ProblemResult)(nil),            // 8: api.core.v1.contest_log.ProblemResult
	(*GetContestRankingRes)(nil),     // 9: api.core.v1.contest_log.GetContestRankingRes
}
var file_core_v1_contest_log_contest_proto_depIdxs = []int32{
	0, // 0: api.core.v1.contest_log.GetContestListRes.data:type_name -> api.core.v1.contest_log.ContestLog
	0, // 1: api.core.v1.contest_log.GetUserContestHistoryRes.data:type_name -> api.core.v1.contest_log.ContestLog
	8, // 2: api.core.v1.contest_log.RankingItem.problem_results:type_name -> api.core.v1.contest_log.ProblemResult
	0, // 3: api.core.v1.contest_log.GetContestRankingRes.contest:type_name -> api.core.v1.contest_log.ContestLog
	6, // 4: api.core.v1.contest_log.GetContestRankingRes.data:type_name -> api.core.v1.contest_log.RankingItem
	7, // 5: api.core.v1.contest_log.GetContestRankingRes.problems:type_name -> api.core.v1.contest_log.ProblemColumn
	1, // 6: api.core.v1.contest_log.Contest.GetContestList:input_type -> api.core.v1.contest_log.GetContestListReq
	3, // 7: api.core.v1.contest_log.Contest.GetUserContestHistory:input_type -> api.core.v1.contest_log.GetUserContestHistoryReq
	5, // 8: api.core.v1.contest_log.Contest.GetContestRanking:input_type -> api.core.v1.contest_log.GetContestRankingReq
	2, // 9: api.core.v1.contest_log.Contest.GetContestList:output_type -> api.core.v1.contest_log.GetContestListRes
	4, // 10: api.core.v1.contest_log.Contest.GetUserContestHistory:output_type -> api.core.v1.contest_log.GetUserContestHistoryRes
	9, // 11: api.core.v1.contest_log.Contest.GetContestRanking:output_type -> api.core.v1.contest_log.GetContestRankingRes
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_core_v1_contest_log_contest_proto_init() }
func file_core_v1_contest_log_contest_proto_init() {
	if File_core_v1_contest_log_contest_proto != nil {
		return
	}
	file_core_v1_contest_log_contest_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_contest_log_contest_proto_rawDesc), len(file_core_v1_contest_log_contest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_contest_log_contest_proto_goTypes,
		DependencyIndexes: file_core_v1_contest_log_contest_proto_depIdxs,
		MessageInfos:      file_core_v1_contest_log_contest_proto_msgTypes,
	}.Build()
	File_core_v1_contest_log_contest_proto = out.File
	file_core_v1_contest_log_contest_proto_goTypes = nil
	file_core_v1_contest_log_contest_proto_depIdxs = nil
}
